NUMPY RANDOM MODULE
*rand: Random values in a given shape
*randn:Return a sample from the "standard normal distribution"
*randint:Returns random integer from low(inclusive) to high(exclusive).
*random:Returns random floats in the half-open interval
*choice:Generate a random sample from a given 1-D array.
*shuffle:Shuffle the contents of the sequence 




In [1]:
import numpy as np

In [15]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
print(a+5)

[ 5  6  7  8  9 10 11 12 13 14]


In [17]:
#np.random.seed(1)
np.random.shuffle(a)
print(a)

[8 3 5 9 0 6 1 7 4 2]


In [18]:
#Returns values from a Standard Normal Distriibution
a=np.random.randn(2,3)
print(a)

[[ 0.7299756   0.37299379  0.53381091]
 [-0.0919733   1.91382039  0.33079713]]


In [19]:
a=np.random.randint(5,10,3)
print(a)

[6 8 9]


In [20]:
#Randomly pick one element from a array
element=np.random.choice([1,4,3,27,11])
print(element)

3


Some more numpy functions-statistics
min,max
mean
median
average
variance
standard deviation


In [22]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [23]:
print(np.min(a))

1


In [24]:
#specify axis for the direction in case of multidimensional array
print(np.min(a,axis=0))
print(np.min(a,axis=1))

[1 2 3 4]
[1 5]


In [25]:
#Mean average of all the elements
print(np.mean(a))



4.5


In [26]:
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

[3. 4. 5. 6.]
[2.5 6.5]


In [27]:
b=np.array([1,5,4,2,0])
print(np.median(b))

2.0


In [30]:
#mean vs average is weighted
print(np.mean(b))
w=np.array([1,2,3,4,5])
print(np.average(b,weights=w))

2.4
2.066666666666667


In [33]:
#standard deviation
u=np.mean(b)
mystd=np.sqrt(np.mean(abs(b-u)**2))
print(mystd)
#inbuilt function
print(np.std(b))

1.854723699099141
1.854723699099141


In [34]:
#variance
print(mystd**2)
print(np.var(b))

3.440000000000001
3.4400000000000004
