In [1]:
# Numpy Basics

In [2]:
import numpy as np

In [128]:
a=np.array([1,2,3,4,5])

In [129]:
print(a)

[1 2 3 4 5]


In [130]:
print(type(a))

<class 'numpy.ndarray'>


In [131]:
print(a.shape) #linear array

(5,)


In [7]:
b = np.array([[1],[2],[3],[4],[5]])

In [8]:
b

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [9]:
print(type(a))

<class 'numpy.ndarray'>


In [10]:
print(b.shape)  ## 2D-array

(5, 1)


In [12]:
b[0][0]

1

In [14]:
b[1][0]

2

In [15]:
c=np.array([[1,2,3],[4,5,6]])

In [16]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
print(type(c))

<class 'numpy.ndarray'>


In [18]:
print(c.shape)

(2, 3)


In [20]:
c[1][2]

6

In [21]:
# Create Zeros,Ones, Custom array
d=np.zeros((3,3))

In [23]:
d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
e=np.ones((3,3))

In [25]:
e

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
#Array of some constants
f=np.full((3,2),5)
f

array([[5, 5],
       [5, 5],
       [5, 5]])

In [27]:
#Identity matrix
g=np.eye(3)

In [28]:
g

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
#Random Matrix
rm=np.random.random((2,3))

In [30]:
rm

array([[0.15651875, 0.31600969, 0.28555816],
       [0.61627586, 0.05312893, 0.97841172]])

In [32]:
print(rm[ : ,0])          

[0.15651875 0.61627586]


rm[1,1:]=2

In [35]:
rm[1,1:]=2            ## slicing
print(rm)

[[0.15651875 0.31600969 0.28555816]
 [0.61627586 2.         2.        ]]


In [46]:
## set some rows and columns with any values
z=np.zeros((3,3),dtype=np.int64)

In [47]:
z

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [48]:
z[1, : ]=1
print(z)

[[0 0 0]
 [1 1 1]
 [0 0 0]]


In [49]:
z[:,-1]=5
print(z)

[[0 0 5]
 [1 1 5]
 [0 0 5]]


In [50]:
#Datatypes
print(z.dtype)

int64


In [51]:
#Mathematical operations
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

In [70]:
print(x,y)

[[1 2]
 [3 4]] [[5 6]
 [7 8]]


In [53]:
x+y

array([[ 6,  8],
       [10, 12]])

In [54]:
y-y

array([[0, 0],
       [0, 0]])

In [55]:
np.add(x,y)

array([[ 6,  8],
       [10, 12]])

In [57]:
np.subtract(x,y)


array([[-4, -4],
       [-4, -4]])

In [58]:
x-y

array([[-4, -4],
       [-4, -4]])

In [59]:
print(x*y)
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [60]:
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [61]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [62]:
#Matrix multiplication/dot products
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [63]:
print(x.dot(x))

[[ 7 10]
 [15 22]]


In [64]:
print(x.dot(y))

[[19 22]
 [43 50]]


In [65]:
print(np.dot(x,y))

[[19 22]
 [43 50]]


In [66]:
#Multiplication(Dot Product) of vectors - scalar
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
print(a.dot(b))

30


In [67]:
print(a)

[1 2 3 4]


In [68]:
print(sum(a))

10


In [71]:
print(x)

[[1 2]
 [3 4]]


In [75]:
print(np.sum(x))
print(np.sum(x,axis=1))
print(np.sum(x,axis=0))

10
[3 7]
[4 6]


In [136]:
#stacking of array
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
print(a)
b=b+5
print(b)
print(type(b))
print(b.shape)

[1 2 3 4]
[6 7 8 9]
<class 'numpy.ndarray'>
(4,)


In [138]:
x=print(np.stack((a,b),axis=1))
y=print(np.stack((a,b),axis=0))
print(x.shape)

[[1 6]
 [2 7]
 [3 8]
 [4 9]]
[[1 2 3 4]
 [6 7 8 9]]


AttributeError: 'NoneType' object has no attribute 'shape'

In [141]:
#Reshape of array
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [142]:
np.reshape(a,6)

array([1, 2, 3, 4, 5, 6])

In [143]:
np.reshape(a,(3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [144]:
np.reshape(a,(6,-1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])